### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by reihoron** [Adrian400811/VehicleSim#1]
Top: Highest Priority
- [x] #10
- [x] JavaDoc
- [x] New Pedestrian (Part 2)
    - [x] #13
    - [x] #14

- [x] Effects
    - [x] Car crash (Part 4)
    - [x] Towing
    - [x] Explosions (Part 6)
    - [x] Pedestrian Screaming (Part 6)
    - [x] Air Raid (Part 3)
- [x] Object behaviors
    - [x] Crash into another car, not slow down (Part 4)
    - [x] Ambulance pick up knocked down
    - [x] #4 (Part 3)
- [x] New Vehicles
    - [x] Tow truck (Part 1)

**Comment by Adrian400811** [comment]
Optional:
- [ ] Stats bar
    - [ ] Generated vehicles
    - [ ] Exploded vehicles
    - [ ] Generated peds
    - [ ] Knocked down peds
    - [ ] Ambulance spawned
    - [ ] Tow truck spawned
- [ ] Setting page
    - [ ] Turn off certain effects
    - [ ] Turn off Stats bar
    - [ ] Adjust screaming volume
